import pandas as pd
import numpy as np
data = np.array(['a','b','c','d'])
s = pd.Series(data)
print(s)
print("indexing")
s = pd.Series(data,index=[100,101,102,103])
print(s)
print("Aliasing")
data = {'a' : 0., 'b' : 1., 'c' : 2.}
s = pd.Series(data)
print(s)
data = {'a' : 0., 'b' : 1., 'c' : 2.}
s = pd.Series(data,index=['b','c','d','a'])
print(s)
print("scalar series")
s = pd.Series(5,index=[0, 1, 2, 3])
print(s)
print("Dataframe")
data = [['rekha',10],['rohini',12],['geetha',13]]
df = pd.DataFrame(data,columns=['Name','Age'])
print(df)
print(df.T)
print(df.shape)
s = pd.Series(np.random.randn(4))
print(s)
print(s.values)
unsorted_df = pd.DataFrame(np.random.randn(10,2),index=[1,4,6,2,3,5,9,8,0,7],columns = ['col2','col1'])
sorted_df=unsorted_df.sort_index()
print(sorted_df)